### ISSUE TITLE
how to install this plugin ?

### ISSUE THREAD

**Issue by mayersgamer** [NiGHT757/AFKManager#10]
reupload it organized ,like file called addons and we just put the folder in server , i dont know where to put them files

**Comment by NiGHT757** [comment]
> reupload it organized ,like file called addons and we just put the folder in server , i dont know where to put them files

Have you read CSS docs and the readme file from this repository ?
If yes, extract AFKManager folder from .zip and add it to “plugins” folder in CSS folder.

https://github.com/NiGHT757/AFKManager/releases/tag/v0.0.8
