### ISSUE TITLE
kicking admin only 

### ISSUE THREAD

**Issue by mayersgamer** [NiGHT757/AFKManager#11]
its not kicking players 
and how to not kick spectator i just want the plugin to switch pplayers to spec

**Comment by NiGHT757** [comment]
> its not kicking players and how to not kick spectator i just want the plugin to switch pplayers to spec

If you don't want to kick spectators, just set SpecKickPlayerAfterXWarnings to 0.
There is a problem with the timer, sometime stops for no reason, i need to check.
