### ISSUE TITLE
Bug Anti-Camp-Timer

### ISSUE THREAD

**Issue by Marfeld** [NiGHT757/AFKManager#23]
I think there is still a mistake. For me the anti-camp uses the AFK timer and not the AntiCampWarnPlayerEveryXSeconds timer. Regards Mafel

**Comment by NiGHT757** [comment]
Please try again with [v0.2.4](https://github.com/NiGHT757/AFKManager/releases/tag/v0.2.4)

**Comment by Marfeld** [comment]
Works perfectly now. Thank you :)
