### ISSUE TITLE
[BUG] Kick message from spectate

### ISSUE THREAD

**Issue by csportalsk** [NiGHT757/AFKManager#27]
When player is moved to spectate for AFK -> message for player in spectate is showed for everyone. What is wrong. Only message _[AFK] player was kicked for being AFK_ might be showed for everyone. Right?

```
[AFK] You're Idle/AFK. Move or you'll be kicked in 30.0 seconds. <- this
[AFK] You're Idle/AFK. Move or you'll be kicked in 20.0 seconds. <- this
[AFK] You're Idle/AFK. Move or you'll be kicked in 10.0 seconds. <- this

[AFK] wimmyjalker was kicked for being AFK.
```

"AFK Manager" (0.2.5)
Current API Version: v247 (1.0.247+f8451c2)

**Comment by NiGHT757** [comment]
Fixed in [v0.2.6](https://github.com/NiGHT757/AFKManager/releases/tag/v0.2.6)
