### ISSUE TITLE
Whitelist improvements during AFK verification

### ISSUE THREAD

**Issue by crashzk** [NiGHT757/AFKManager#3]
It would be possible to make all players pass the check to be moved to SPEC if they are AFK, but for them to be kicked from the server even if they are AFK from SPEC only if the player is not on the whitelist.

In other words, all players can be moved to SPEC if they are AFK and if they continue AFK in SPEC, if the player is not on the whitelist, he will be kicked from the server.

**Comment by NiGHT757** [comment]
> It would be possible to make all players pass the check to be moved to SPEC if they are AFK, but for them to be kicked from the server even if they are AFK from SPEC only if the player is not on the whitelist.
> 
> In other words, all players can be moved to SPEC if they are AFK and if they continue AFK in SPEC, if the player is not on the whitelist, he will be kicked from the server.

I think i'll just add 2 more options in config for whitelist.
`"WhiteListUsers": {
    "76561198143759075": {
      "SkipAFK": true,
      "SkipSPEC": false
    }
  }`
  SkipAFK - will skip afk verification
  SkipSPEC - will skip SPEC
  What do u think?

**Comment by crashzk** [comment]
> > It would be possible to make all players pass the check to be moved to SPEC if they are AFK, but for them to be kicked from the server even if they are AFK from SPEC only if the player is not on the whitelist.
> > In other words, all players can be moved to SPEC if they are AFK and if they continue AFK in SPEC, if the player is not on the whitelist, he will be kicked from the server.
> 
> I think i'll just add 2 more options in config for whitelist. `"WhiteListUsers": { "76561198143759075": { "SkipAFK": true, "SkipSPEC": false } }` SkipAFK - will skip AFK verification. SkipSPEC - will skip those who are on the SPEC team. ( for future updates ) What do you think?

Perfect, I believe this helps a lot.

**Comment by NiGHT757** [comment]
> > > It would be possible to make all players pass the check to be moved to SPEC if they are AFK, but for them to be kicked from the server even if they are AFK from SPEC only if the player is not on the whitelist.
> > > In other words, all players can be moved to SPEC if they are AFK and if they continue AFK in SPEC, if the player is not on the whitelist, he will be kicked from the server.
> > 
> > 
> > I think i'll just add 2 more options in config for whitelist. `"WhiteListUsers": { "76561198143759075": { "SkipAFK": true, "SkipSPEC": false } }` SkipAFK - will skip AFK verification. SkipSPEC - will skip those who are on the SPEC team. ( for future updates ) What do you think?
> 
> Perfect, I believe this helps a lot.

[Ready](https://github.com/NiGHT757/AFKManager/releases/tag/v0.0.5) I hope :)
