### ISSUE TITLE
Improvements to the punishment system

### ISSUE THREAD

**Issue by crashzk** [NiGHT757/AFKManager#4]
Punishment system with sum for carrying out actions.

Currently you would have these options:
```
Punishment options (0 - kill | 1 - kill + move to spectator | 2 - kick)
```
It would work like this 1 + 2 = 3

That is, the user would receive Kill + Move to Spectator + Kick later if he continues AFK from SPEC.

Testing here I haven't been able to reproduce this way yet.

**Comment by NiGHT757** [comment]
I made this option in config [v0.0.6](https://github.com/NiGHT757/AFKManager/releases/tag/v0.0.6)
So i don't think it's necessary to create that sum because these options are specifically designed for handling AFK players when they are in a playable team.

In my opinion there is no reason for example to kill player + move to spec + kick.
For AFK players in the SPEC team, there is only one option, which is to kick them.

Maybe i'm wrong :)

**Comment by crashzk** [comment]
In this case, I would like to leave it as...

All users will be moved to SPEC if they become AFK, regardless of whether the player is on the whitelist.

Oh yes, players who are on SPEC if they continue AFK, they will be kicked, but players who are on the whitelist will not be kicked, they will stay on SPEC even though they are AFK.

Did you understand more or less? Would it currently be possible with the plugin?

**Comment by NiGHT757** [comment]
> In this case, I would like to leave it as...
> 
> All users will be moved to SPEC if they become AFK, regardless of whether the player is on the whitelist.
> 
> Oh yes, players who are on SPEC if they continue AFK, they will be kicked, but players who are on the whitelist will not be kicked, they will stay on SPEC even though they are AFK.
> 
> Did you understand more or less? Would it currently be possible with the plugin?
> 
> Configuration I currently use:
> 
> ```
> {
>   "WhiteListUsers": {
>     "76561198088290585": {
>       "SkipAFK": false,
>       "SkipSPEC": true
>     }
>   },
>   "ChatPrefix": "[ {DarkRed}AFK Mangaer {Default}]",
>   "ChatKickMessage": "{chatprefix} {Green}{playername} {Default}foi kickado por esta AFK.",
>   "ChatMoveMessage": "{chatprefix} {Green}{playername} {Default}foi movido para SPEC por esta AFK.",
>   "ChatKillMessage": "{chatprefix} {Green}{playername} {Default}foi morto por esta AFK.",
>   "ChatWarningKickMessage": "{chatprefix} You\u0027re {Green}AFK{Default}. Move or you\u0027ll be kicked in {Darkred}{time}{Default} seconds.",
>   "ChatWarningMoveMessage": "{chatprefix} You\u0027re {Green}AFK{Default}. Move or you\u0027ll be moved to SPEC in {Darkred}{time}{Default} seconds.",
>   "ChatWarningKillMessage": "{chatprefix} You\u0027re {Green}AFK{Default}. Move or you\u0027ll killed in {Darkred}{time}{Default} seconds.",
>   "Warnings": 3,
>   "Punishment": 2,
>   "SpecWarnPlayerEveryXSeconds": 15,
>   "SpecKickPlayerAfterXWarnings": 5,
>   "Timer": 5,
>   "Offset": 89
> }
> ```
"players who are on SPEC if they continue AFK, they will be kicked, but players who are on the whitelist will not be kicked, they will stay on SPEC even though they are AFK."

here you mean if the player is moved by the afk plugin and then he will continue to be AFK in SPEC to be kicked?
"SkipSPEC" will skip afk check for some spectators players.

**Comment by crashzk** [comment]
> here you mean if the player is moved by the afk plugin and then he will continue to be AFK in SPEC to be kicked? "SkipSPEC" will skip afk check for some spectators players.

That's correct. It would be possible?

**Comment by NiGHT757** [comment]
> > here you mean if the player is moved by the afk plugin and then he will continue to be AFK in SPEC to be kicked? "SkipSPEC" will skip afk check for some spectators players.
> 
> That's correct. It would be possible?

yes

**Comment by NiGHT757** [comment]
> > here you mean if the player is moved by the afk plugin and then he will continue to be AFK in SPEC to be kicked? "SkipSPEC" will skip afk check for some spectators players.
> 
> That's correct. It would be possible?

Please test this again in https://github.com/NiGHT757/AFKManager/releases/tag/v0.0.8 .
There is an option in config "SpecKickOnlyMovedByPlugin" that is "false" by default.
