### ISSUE TITLE
Spec 

### ISSUE THREAD

**Issue by audiomaster99** [NiGHT757/AFKManager#5]
hey just wanted to ask does the plugin only check for players in spec that were moved for afk, or also cheks for players who joined spec on their own?

**Comment by NiGHT757** [comment]
> hey just wanted to ask does the plugin only check for players in spec that were moved for afk, or also cheks for players who joined spec on their own?

This plugin also checks all players that are in spec team, doesn't matter if they were moved by plugin or manually.

**Comment by audiomaster99** [comment]
> > hey just wanted to ask does the plugin only check for players in spec that were moved for afk, or also cheks for players who joined spec on their own?
> 
> This plugin also checks all players that are in spec team, doesn't matter if they were moved by plugin or manually.

sorry for bothering one more question, can I disable cheking players in spec?

**Comment by NiGHT757** [comment]
> > > hey just wanted to ask does the plugin only check for players in spec that were moved for afk, or also cheks for players who joined spec on their own?
> 
> > 
> 
> > This plugin also checks all players that are in spec team, doesn't matter if they were moved by plugin or manually.
> 
> 
> 
> sorry for bothering one more question, can I disable cheking players in spec?

Please read readme file and search for SpecKickPlayerAfterXWarnings
