### ISSUE TITLE
[REG] don't count BOTs to count players

### ISSUE THREAD

**Issue by csportalsk** [NiGHT757/AFKManager#6]
Hi,

it will be good if it will be posible doesn't count BOTs to count players.
When you set `"SpecKickMinPlayers": 4,` and 2 players and 2 BOTs are on server, you lost player while he can be still in spectate.
Players checking how many plaers are on the server and then connect. Server can by this way filled earlier.

**Comment by NiGHT757** [comment]
Fixed in https://github.com/NiGHT757/AFKManager/releases/tag/v0.0.8
