### ISSUE TITLE
[BUG] Kicked by AFK if joining directly from SPEC

### ISSUE THREAD

**Issue by crashzk** [NiGHT757/AFKManager#8]
I'm connecting to the server and going straight in to spec, but even though I'm moving between the players' cameras, typing in chat, etc., I'm kicked off the server for still being AFK.

**Comment by NiGHT757** [comment]
> I'm connecting to the server and going straight in to spec, but even though I'm moving between the players' cameras, typing in chat, etc., I'm kicked off the server for still being AFK.

The are no checks if the player is AFK at SPEC, they simply cannot stay at SPEC for x amount of time.

**Comment by crashzk** [comment]
> > I'm connecting to the server and going straight in to spec, but even though I'm moving between the players' cameras, typing in chat, etc., I'm kicked off the server for still being AFK.
> 
> The are no checks if the player is AFK at SPEC, they simply cannot stay at SPEC for x amount of time.

Ok, even though I have access to the flag then I will still get kicked, right? In this case, I am an administrator and I was kicked while on SPEC.

**Comment by NiGHT757** [comment]
> > > I'm connecting to the server and going straight in to spec, but even though I'm moving between the players' cameras, typing in chat, etc., I'm kicked off the server for still being AFK.
> > 
> > 
> > The are no checks if the player is AFK at SPEC, they simply cannot stay at SPEC for x amount of time.
> 
> Ok, even though I have access to the flag then I will still get kicked, right? In this case, I am an administrator and I was kicked while on SPEC.

Do you have "SpecSkipFlag" configured? If yes, flag doesn't work properly?

**Comment by crashzk** [comment]
> > > > I'm connecting to the server and going straight in to spec, but even though I'm moving between the players' cameras, typing in chat, etc., I'm kicked off the server for still being AFK.
> > > 
> > > 
> > > The are no checks if the player is AFK at SPEC, they simply cannot stay at SPEC for x amount of time.
> > 
> > 
> > Ok, even though I have access to the flag then I will still get kicked, right? In this case, I am an administrator and I was kicked while on SPEC.
> 
> Do you have "SpecSkipFlag" configured? If yes, flag doesn't work properly?

I believe it could be that... It's configured like this:
```
  "SpecSkipFlag": "@css/skipspec",
  "SkipFlag": "@css/skipafk"
  ```
  
I'm using the CSSharp group admin system, so I don't need to configure these two cvars in the admin group itself, or change this cvar to `@css/vip` for example for it to work, correct?

**Comment by NiGHT757** [comment]
> > > > > I'm connecting to the server and going straight in to spec, but even though I'm moving between the players' cameras, typing in chat, etc., I'm kicked off the server for still being AFK.
> > > > 
> > > > 
> > > > The are no checks if the player is AFK at SPEC, they simply cannot stay at SPEC for x amount of time.
> > > 
> > > 
> > > Ok, even though I have access to the flag then I will still get kicked, right? In this case, I am an administrator and I was kicked while on SPEC.
> > 
> > 
> > Do you have "SpecSkipFlag" configured? If yes, flag doesn't work properly?
> 
> I believe it could be that... It's configured like this:
> 
> ```
>   "SpecSkipFlag": "@css/skipspec",
>   "SkipFlag": "@css/skipafk"
> ```
> 
> I'm using the CSSharp group admin system, so I don't need to configure these two cvars in the admin group itself, or change this cvar to `@css/vip` for example for it to work, correct?

If you need to skip these flags for check, you need to add them for every admin u want in admins.json file from CSS.
Make sure admins have these flags from "SpecSkipFlag" and / or "SkipFlag".
